FROM node:11.13.0-alpine

# create destination directory
ENV APP_ROOT .
RUN mkdir ${APP_ROOT}
WORKDIR ${APP_ROOT}

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git

# copy the app, note .dockerignore
COPY . ${APP_ROOT}
RUN npm install

# build necessary, even if no static files are needed,
# since it builds the server as well
RUN npm run build

# expose 5000 on container
EXPOSE 5000

# set app serving to permissive / assigned
ENV NUXT_HOST=0.0.0.0
# set app port
ENV NUXT_PORT=5000

# start the app
CMD [ "npm", "start" ]