module.exports = {
    plugins: ['stylelint-order'],
    rules: {
        'color-hex-case': 'lower',
        'color-hex-length': 'long',
        'no-empty-source': null,
        'declaration-block-no-duplicate-properties': true,
        'rule-empty-line-before': 'never',
        'declaration-empty-line-before': 'never',
        'font-weight-notation': 'numeric',
        'order/order': [
            'custom-properties',
            'dollar-variables',
            {
                type: 'at-rule',
                name: 'include',
                parameter: 'clearfix',
            },
            {
                type: 'at-rule',
                name: 'include',
                parameter: 'visuallyhidden',
            },
            {
                type: 'at-rule',
                name: 'include',
                parameter: 'rem-typo',
            },
            'declarations',
            {
                type: 'rule',
                selector: /^&:\w+$/,
            },
            {
                type: 'at-rule',
                name: 'include',
                parameter: 'colorize',
            },
            'rules',
            {
                type: 'at-rule',
                hasBlock: true,
            },
            {
                type: 'at-rule',
                name: 'include',
                parameter: 'breakpoint',
                hasBlock: true,
            },
            {
                type: 'at-rule',
                name: 'include',
                parameter: 'respond-to',
                hasBlock: true,
            },
        ],
        'order/properties-order': [
            'content',
            'display',
            'vertical-align',
            'z-index',
            'position',
            'top',
            'right',
            'bottom',
            'left',
            'visibility',
            'float',
            'clear',
            'overflow',
            'overflow-x',
            'overflow-y',
            'clip',
            'zoom',
            'flex-direction',
            'flex-order',
            'flex-pack',
            'flex-align',
            'box-sizing',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'margin',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'padding',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
            'font',
            'font-family',
            'font-size',
            'font-weight',
            'font-style',
            'font-variant',
            'font-size-adjust',
            'font-stretch',
            'font-effect',
            'font-emphasize',
            'font-emphasize-position',
            'font-emphasize-style',
            'font-smooth',
            'line-height',
            'white-space',
            'text-align',
            'text-decoration',
            'text-emphasis',
            'text-emphasis-color',
            'text-emphasis-style',
            'text-emphasis-position',
            'text-indent',
            'text-justify',
            'letter-spacing',
            'word-spacing',
            'text-outline',
            'text-transform',
            'text-wrap',
            'text-overflow',
            'text-overflow-ellipsis',
            'text-overflow-mode',
            'word-wrap',
            'word-break',
            'tab-size',
            'hyphens',
            'color',
            'fill',
            'pointer-events',
            'opacity',
            'filter:progid:DXImageTransform.Microsoft.Alpha(Opacity',
            'border',
            'border-width',
            'border-style',
            'border-color',
            'border-top',
            'border-top-width',
            'border-top-style',
            'border-top-color',
            'border-right',
            'border-right-width',
            'border-right-style',
            'border-right-color',
            'border-bottom',
            'border-bottom-width',
            'border-bottom-style',
            'border-bottom-color',
            'border-left',
            'border-left-width',
            'border-left-style',
            'border-left-color',
            'border-radius',
            'border-top-left-radius',
            'border-top-right-radius',
            'border-bottom-right-radius',
            'border-bottom-left-radius',
            'border-image',
            'border-image-source',
            'border-image-slice',
            'border-image-width',
            'border-image-outset',
            'border-image-repeat',
            'outline',
            'outline-width',
            'outline-style',
            'outline-color',
            'outline-offset',
            'background',
            'filter:progid:DXImageTransform.Microsoft.AlphaImageLoader',
            'background-color',
            'background-image',
            'background-repeat',
            'background-attachment',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-clip',
            'background-origin',
            'background-size',
            'box-decoration-break',
            'box-shadow',
            'filter:progid:DXImageTransform.Microsoft.gradient',
            'text-shadow',
            'table-layout',
            'empty-cells',
            'caption-side',
            'border-spacing',
            'border-collapse',
            'list-style',
            'list-style-position',
            'list-style-type',
            'list-style-image',
            'quotes',
            'counter-reset',
            'counter-increment',
            'resize',
            'cursor',
            'user-select',
            'nav-index',
            'nav-up',
            'nav-right',
            'nav-down',
            'nav-left',
            'transition',
            'transition-delay',
            'transition-timing-function',
            'transition-duration',
            'transition-property',
            'transform',
            'transform-origin',
            'animation',
            'animation-name',
            'animation-duration',
            'animation-play-state',
            'animation-timing-function',
            'animation-delay',
            'animation-iteration-count',
            'animation-direction',
            'text-align-last',
        ],
    },
};
